#!/bin/sh
# End-to-end auth + API smoke test against a running dev server.
# Verifies that protected routes actually reject unauthenticated callers.
B=http://127.0.0.1:7949
T=${SP_TMP:-/tmp}
# Credentials are generated by scripts/setup-test-env.sh, never hardcoded.
. "$T/sp-test-creds.sh"
K="$API_KEY"
P="$DASHBOARD_PASSWORD"
fail=0

code() { curl -s -o "$T/body.txt" -w '%{http_code}' "$@"; }
expect() { # expect <label> <want> <got>
  if [ "$2" = "$3" ]; then echo "  ok   $1 -> $3"
  else echo "  FAIL $1 -> got $3, want $2"; cat "$T/body.txt"; fail=1; fi
}

echo "== unauthenticated must be rejected =="
expect "GET /api/accounts"      401 "$(code $B/api/accounts)"
expect "GET /api/posts"         401 "$(code $B/api/posts)"
expect "POST /api/worker/tick"  401 "$(code -X POST $B/api/worker/tick)"
expect "POST /api/publish"      401 "$(code -X POST $B/api/publish/threads -H 'Content-Type: application/json' -d '{"text":"pwned"}')"
expect "GET / redirects"        307 "$(code $B/)"

echo "== health is public =="
expect "GET /api/health"        200 "$(code $B/api/health)"

echo "== wrong password rejected =="
expect "bad login"              401 "$(code -X POST $B/api/login -H 'Content-Type: application/json' -d '{"password":"wrong"}')"

echo "== api key works =="
expect "tick with key"          200 "$(code -X POST $B/api/worker/tick -H "Authorization: Bearer $K")"
grep -q nothing_due "$T/body.txt" && echo "  ok   tick idle -> nothing_due" || { echo "  FAIL tick payload"; cat "$T/body.txt"; fail=1; }

expect "bad key rejected"       401 "$(code -X POST $B/api/worker/tick -H 'Authorization: Bearer wrong-key-here')"
expect "accounts with key"      200 "$(code $B/api/accounts -H "Authorization: Bearer $K")"
grep -q access_token "$T/body.txt" && { echo "  FAIL accounts leak a token"; fail=1; } || echo "  ok   accounts carry no token"
expect "accounts PATCH with key" 401 "$(code -X PATCH $B/api/accounts -H "Authorization: Bearer $K" -H 'Content-Type: application/json' -d '{"id":1,"enabled":false}')"

echo "== session login works =="
expect "good login"             200 "$(code -c "$T/jar.txt" -X POST $B/api/login -H 'Content-Type: application/json' -d "{\"password\":\"$P\"}")"
expect "accounts with session"  200 "$(code -b "$T/jar.txt" $B/api/accounts)"

echo "== oauth connect needs login + state =="
expect "authorize without login"   401 "$(code $B/api/auth/threads/authorize)"
expect "callback without login"    400 "$(code "$B/api/auth/threads/callback?code=x&state=y")"
expect "authorize with login"      307 "$(code -b "$T/jar.txt" -c "$T/jar.txt" -D "$T/headers.txt" $B/api/auth/threads/authorize)"
grep -qi '^location:.*state=' "$T/headers.txt" && grep -q sp_oauth_state "$T/jar.txt" \
  && echo "  ok   authorize sends state + sets cookie" || { echo "  FAIL authorize state"; cat "$T/headers.txt"; fail=1; }
# the state cookie is now in the jar, so this fails on the mismatch itself
expect "callback with forged state" 400 "$(code -b "$T/jar.txt" "$B/api/auth/threads/callback?code=x&state=forged")"

echo "== input validation =="
expect "missing text"           400 "$(code -X POST $B/api/publish/threads -H "Authorization: Bearer $K" -H 'Content-Type: application/json' -d '{}')"
expect "http image rejected"    400 "$(code -X POST $B/api/publish/threads -H "Authorization: Bearer $K" -H 'Content-Type: application/json' -d '{"text":"x","imageUrl":"http://insecure/x.jpg","kind":"news"}')"

echo "== queue + dedup =="
expect "queue needs media"      400 "$(code -X POST $B/api/posts -H "Authorization: Bearer $K" -H 'Content-Type: application/json' -d '{"caption":"hello"}')"
expect "image + video rejected" 400 "$(code -X POST $B/api/posts -H "Authorization: Bearer $K" -H 'Content-Type: application/json' -d '{"caption":"x","imageUrl":"https://a/x.jpg","videoUrl":"https://a/x.mp4"}')"
grep -q items_without_media "$T/body.txt" && echo "  ok   both media -> items_without_media" || { echo "  FAIL both media payload"; cat "$T/body.txt"; fail=1; }
expect "video passes media check" 400 "$(code -X POST $B/api/posts -H "Authorization: Bearer $K" -H 'Content-Type: application/json' -d '{"caption":"x","videoUrl":"https://a/x.mp4"}')"
grep -q items_without_media "$T/body.txt" && { echo "  FAIL video rejected as missing media"; cat "$T/body.txt"; fail=1; } || echo "  ok   video accepted as media"
expect "queue needs kind"       400 "$(code -X POST $B/api/posts -H "Authorization: Bearer $K" -H 'Content-Type: application/json' -d '{"caption":"x","imageUrl":"https://a/x.jpg"}')"
grep -q items_with_invalid_kind "$T/body.txt" && echo "  ok   no kind -> items_with_invalid_kind" || { echo "  FAIL kind payload"; cat "$T/body.txt"; fail=1; }
expect "wrong-case kind"        400 "$(code -X POST $B/api/posts -H "Authorization: Bearer $K" -H 'Content-Type: application/json' -d '{"caption":"x","imageUrl":"https://a/x.jpg","kind":"News"}')"
expect "publish needs kind"     400 "$(code -X POST $B/api/publish/threads -H "Authorization: Bearer $K" -H 'Content-Type: application/json' -d '{"text":"x","imageUrl":"https://a/x.jpg"}')"

# Last: this fills the limiter for 10.9.9.9. A spoofed first X-Forwarded-For
# entry must not reset it; only the hop nginx appends counts.
echo "== login rate limit keys on the real client =="
for i in 1 2 3 4 5; do
  code -X POST $B/api/login -H "X-Forwarded-For: 6.6.6.$i, 10.9.9.9" -H 'Content-Type: application/json' -d '{"password":"wrong"}' >/dev/null
done
expect "6th try, new spoofed IP" 429 "$(code -X POST $B/api/login -H 'X-Forwarded-For: 7.7.7.7, 10.9.9.9' -H 'Content-Type: application/json' -d '{"password":"wrong"}')"

[ $fail -eq 0 ] && echo "ALL PASS" || echo "FAILURES PRESENT"
exit $fail
