#!/bin/sh
# End-to-end auth + API smoke test against a running dev server.
# Verifies that protected routes actually reject unauthenticated callers.
B=http://127.0.0.1:7949
# Credentials are generated by scripts/setup-test-env.sh, never hardcoded.
. /tmp/sp-test-creds.sh
K="$API_KEY"
P="$DASHBOARD_PASSWORD"
fail=0

code() { curl -s -o /tmp/body.txt -w '%{http_code}' "$@"; }
expect() { # expect <label> <want> <got>
  if [ "$2" = "$3" ]; then echo "  ok   $1 -> $3"
  else echo "  FAIL $1 -> got $3, want $2"; cat /tmp/body.txt; fail=1; fi
}

echo "== unauthenticated must be rejected =="
expect "GET /api/accounts"      401 "$(code $B/api/accounts)"
expect "GET /api/posts"         401 "$(code $B/api/posts)"
expect "POST /api/worker/tick"  401 "$(code -X POST $B/api/worker/tick)"
expect "POST /api/publish"      401 "$(code -X POST $B/api/publish/threads -H 'Content-Type: application/json' -d '{"text":"pwned"}')"
expect "GET / redirects"        307 "$(code $B/)"

echo "== health is public =="
expect "GET /api/health"        200 "$(code $B/api/health)"

echo "== wrong password rejected =="
expect "bad login"              401 "$(code -X POST $B/api/login -H 'Content-Type: application/json' -d '{"password":"wrong"}')"

echo "== api key works =="
expect "tick with key"          200 "$(code -X POST $B/api/worker/tick -H "Authorization: Bearer $K")"
grep -q nothing_due /tmp/body.txt && echo "  ok   tick idle -> nothing_due" || { echo "  FAIL tick payload"; cat /tmp/body.txt; fail=1; }

expect "bad key rejected"       401 "$(code -X POST $B/api/worker/tick -H 'Authorization: Bearer wrong-key-here')"

echo "== session login works =="
expect "good login"             200 "$(code -c /tmp/jar.txt -X POST $B/api/login -H 'Content-Type: application/json' -d "{\"password\":\"$P\"}")"
expect "accounts with session"  200 "$(code -b /tmp/jar.txt $B/api/accounts)"

echo "== input validation =="
expect "missing text"           400 "$(code -X POST $B/api/publish/threads -H "Authorization: Bearer $K" -H 'Content-Type: application/json' -d '{}')"
expect "http image rejected"    400 "$(code -X POST $B/api/publish/threads -H "Authorization: Bearer $K" -H 'Content-Type: application/json' -d '{"text":"x","imageUrl":"http://insecure/x.jpg"}')"

echo "== queue + dedup =="
expect "queue needs account"    400 "$(code -X POST $B/api/posts -H "Authorization: Bearer $K" -H 'Content-Type: application/json' -d '{"caption":"hello"}')"

[ $fail -eq 0 ] && echo "ALL PASS" || echo "FAILURES PRESENT"
exit $fail
